# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='obj',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('obj', 'email', 'time_creation')]),
        ),
    ]
